package io.connect2.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;


@Data
@DynamoDBTable(tableName = "UserMetaData")
public class UserMetaData {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;

	@DynamoDBAttribute
	private String businessName;

	@DynamoDBAttribute
	private String contactOne;

	@DynamoDBAttribute
	private String contactTwo;

	@DynamoDBAttribute
	private String companyLogoUrl;

	@DynamoDBAttribute
	private String district;

	@DynamoDBAttribute
	private String town;
	
	
}
